'use strict';
const $=id=>document.getElementById(id);
let csrf='',current=null,proposal=null,poll=null,busy=false,shownJob=null;
const titleStatus={draft:'Add source media',queued:'Waiting for analysis',running:'Finding moments',review:'Ready to review',approved:'Choices saved',failed:'Analysis needs attention',cancelled:'Analysis cancelled'};
function text(tag,value,cls){const e=document.createElement(tag);e.textContent=value;if(cls)e.className=cls;return e;}
function sourceTime(seconds){const tenths=Math.round(seconds*10);return `${Math.floor(tenths/600)}:${((tenths%600)/10).toFixed(1).padStart(4,'0')}`;}
function selectionDuration(prop,p){
 const chosen=new Set([...document.querySelectorAll('input[name=moment]:checked')].map(e=>e.value));
 const ranges=prop.moments.filter(m=>chosen.has(m.id)&&Array.isArray(m.clip_range_s)).map(m=>m.clip_range_s).sort((a,b)=>a[0]-b[0]);
 let total=0,end=-Infinity;
 for(const [a,b] of ranges){total+=Math.max(0,b-Math.max(a,end));end=Math.max(end,b);}
 const source=p.uploads.find(u=>u.kind==='video')?.metadata?.duration_seconds;
 $('selection-duration').textContent=source?`Selected source duration: ${total.toFixed(2)} s of ${sourceTime(source)} (${(100*total/source).toFixed(1)}%). Source positions show where moments occur in your video.`:`${chosen.size} source photos selected.`;
}
function notice(value){$('notice').textContent=value;$('notice').hidden=!value;}
async function api(path,options={}){const headers={...(options.body&&!(options.body instanceof Blob)?{'Content-Type':'application/json'}:{}),'X-CSRF-Token':csrf,...options.headers};const res=await fetch('/api'+path,{...options,headers});let data;try{data=await res.json();}catch{data={detail:'The service could not complete this request.'};}if(!res.ok){if(res.status===401){clearInterval(poll);$('login').hidden=false;$('workspace').hidden=true;$('project').hidden=true;}throw new Error(typeof data.detail==='string'?data.detail:JSON.stringify(data.detail));}return data;}
async function act(fn){notice('');try{await fn();}catch(e){notice(e.message);}}
async function session(){const s=await api('/session');csrf=s.csrf;$('name').textContent=s.name;$('login').hidden=true;$('account').hidden=false;await home();}
async function home(){clearInterval(poll);current=null;proposal=null;shownJob=null;history.replaceState(null,'',location.pathname);$('project').hidden=true;$('workspace').hidden=false;$('welcome').hidden=false;const rows=await api('/projects');$('projects').replaceChildren();if(!rows.length){$('projects').append(text('p','Your first trip starts here.','muted'));$('create-form').hidden=false;}for(const p of rows){const b=document.createElement('button');b.className='project-card';b.append(text('strong',p.title),text('small',titleStatus[p.status]||p.status));b.onclick=()=>act(()=>openProject(p.id));$('projects').append(b);}}
async function openProject(id){clearInterval(poll);shownJob=null;proposal=null;$('workspace').hidden=true;$('project').hidden=false;$('welcome').hidden=true;history.replaceState(null,'','#'+id);await refresh(id,true);poll=setInterval(()=>{if(current&&!busy)refresh(current.id,false).catch(e=>notice(e.message));},4000);}
async function refresh(id,initial=false){const p=await api('/projects/'+id);current=p;$('project-title').textContent=p.title;if(initial){$('request').value=p.request;$('context').value=p.context;}$('file-label').hidden=p.revision!==0;$('media').replaceChildren();for(const u of p.uploads){const card=document.createElement('div');card.className='media-item';if(u.status==='ready'){const img=document.createElement('img');img.src=`/api/projects/${id}/uploads/${u.id}/preview`;img.alt=u.name;card.append(img);}card.append(text('p',u.name),text('p',u.status==='ready'?'Ready':`${Math.round(100*u.offset/u.size)}% uploaded · choose this file again to resume`,'muted'));if(p.revision===0&&u.status==='uploading'&&u.offset===u.size){const retry=text('button','Retry validation','quiet');retry.onclick=()=>act(async()=>{await api(`/projects/${id}/uploads/${u.id}/complete`,{method:'POST'});await refresh(id);});card.append(retry);}if(p.revision===0){const b=text('button','Remove','quiet');b.onclick=()=>act(async()=>{await api(`/projects/${id}/uploads/${u.id}`,{method:'DELETE'});await refresh(id);});card.append(b);}$('media').append(card);}
const generationActive=['queued','running'].includes(p.generation?.status);const active=['queued','running'].includes(p.status)||generationActive;renderGeneration(p);$('analyze').disabled=active||!p.uploads.length||p.uploads.some(u=>u.status!=='ready');$('request').disabled=active;$('context').disabled=active;$('analyze').textContent=p.revision?'Analyze revised highlights':'Find my moments';$('job-panel').hidden=!p.job||['review','approved'].includes(p.status);$('cancel').hidden=!active;$('delete').disabled=active;if(p.job){$('job-status').textContent=titleStatus[p.status]||p.status;$('job-stage').textContent=p.job.stage;$('job-detail').textContent=p.job.error||'Your progress is saved. You can leave this page and return later.';document.querySelector('.pulse').hidden=!active;}
for(const step of ['upload','analyze','review','generate'])$('step-'+step).classList.toggle('active',step===(generationActive||p.generation?.status==='ready'?'generate':p.revision===0?'upload':active||['failed','cancelled'].includes(p.status)?'analyze':'review'));
if(['review','approved'].includes(p.status)){if(shownJob!==p.current_job){const result=await api(`/projects/${id}/proposal`);proposal=result;renderReview(result.proposal,p);shownJob=p.current_job;}$('review').hidden=false;$('approval-state').textContent=p.approval?'Your choices are saved.':'';}else{$('review').hidden=true;shownJob=null;}}
function renderReview(prop,p){let summary=$('selection-duration');if(!summary){summary=text('p','','muted');summary.id='selection-duration';$('moments').before(summary);}$('requirements').replaceChildren(text('h3','What the evidence supports'));for(const r of prop.requirements){const row=document.createElement('div');row.className='requirement '+r.status;row.append(text('span',r.status.replaceAll('_',' ')),text('div',r.description));$('requirements').append(row);}for(const a of prop.intent.ambiguities||[])$('requirements').append(text('p',a.question,'muted'));$('moments').replaceChildren();for(const m of prop.moments){const card=document.createElement('article');card.className='moment-card';const media=document.createElement(m.clip?'video':'img');if(m.clip){media.controls=true;media.muted=true;media.playsInline=true;media.preload='none';media.poster=`/api/projects/${p.id}/artifacts/${m.image}`;media.src=`/api/projects/${p.id}/artifacts/${m.clip}`;}else{media.src=`/api/projects/${p.id}/artifacts/${m.image}`;media.alt=m.moment;}card.append(media);const body=document.createElement('div');body.className='moment-body';const label=document.createElement('label'),check=document.createElement('input');check.type='checkbox';check.value=m.id;check.name='moment';check.checked=p.approval?p.approval.moment_ids.includes(m.id):true;label.append(check,document.createTextNode(m.source_kind==='photo'?'Source photo':`Source position ${sourceTime(m.hero_timestamp_s)}`));check.onchange=()=>selectionDuration(prop,p);body.append(label);if(m.clip_range_s){const [start,end]=m.clip_range_s;body.append(text('p',`Preview length ${(end-start).toFixed(2)} s · Source interval ${sourceTime(start)}–${sourceTime(end)}`,'muted'));}body.append(text('p',m.moment),text('p',m.selection_reason,'muted'),text('p',m.reference_limit,'muted'));card.append(body);$('moments').append(card);}if(!prop.moments.length)$('moments').append(text('p','No suitable moments were found. Refine your highlights or add clarification and analyze again.','panel'));selectionDuration(prop,p);$('approve').disabled=!prop.moments.length||['queued','running'].includes(p.generation?.status);$('recommendations').replaceChildren();for(const r of prop.recommendations){$('recommendations').append(text('div',`${prop.styles.find(s=>s.id===r.style)?.name||r.style} · ${r.lighting} — ${r.reason}`,'recommendation'));}$('style').value=p.approval?.style||prop.recommendations[0]?.style||'natural';$('lighting').value=p.approval?.lighting||prop.recommendations[0]?.lighting||'day';$('notes').value=p.approval?.notes||'';}
function renderGeneration(p){
 const g=p.generation,active=['queued','running'].includes(g?.status);$('generation-panel').hidden=false;
 $('generate').hidden=g?.status==='ready';$('generate').disabled=active||!p.approval||!p.generation_available;
 $('generation-heading').textContent=g?.status==='ready'?'Your 3D memory is ready':'Generate your selected moments';$('approve').disabled=active;
 $('generation-stage').textContent=g?(g.error||g.stage):!p.approval?(['review','approved'].includes(p.status)?'Choose moments below and save your choices to enable generation.':'Upload your media, find moments, then save your choices to enable generation.'):!p.generation_available?'Generation is unavailable on this host. Your saved choices are retained.':'Ready to generate from your saved choices.';
 $('generate').textContent=g?.status==='failed'?'Retry generation':'Generate 3D memory';
 $('cancel-generation').hidden=!active;$('open-generation').hidden=g?.status!=='ready';
 if(g?.status==='ready')$('open-generation').href=`/static/generation.html?project=${p.id}&generation=${g.id}`;
 $('generation-timing').textContent=g?.started?`Generation ${g.finished?'time':'elapsed'}: ${((g.finished||Date.now()/1000)-g.started).toFixed(0)} seconds`:'The generation timer starts when the GPU worker begins.';
}
$('jump-generation').onclick=()=>$('generation-panel').scrollIntoView({behavior:'smooth',block:'start'});
$('generate').onclick=()=>act(async()=>{await api(`/projects/${current.id}/generate`,{method:'POST'});await refresh(current.id);});
$('cancel-generation').onclick=()=>act(async()=>{await api(`/projects/${current.id}/generations/${current.generation.id}/cancel`,{method:'POST'});await refresh(current.id);});
$('login-form').onsubmit=e=>{e.preventDefault();act(async()=>{const s=await api('/login',{method:'POST',body:JSON.stringify({code:$('code').value.trim()})});csrf=s.csrf;$('code').value='';await session();});};
$('logout').onclick=()=>act(async()=>{await api('/logout',{method:'POST'});clearInterval(poll);location.reload();});
$('new-project').onclick=()=>{$('create-form').hidden=false;$('create-form').scrollIntoView({behavior:'smooth'});};
$('create-form').onsubmit=e=>{e.preventDefault();act(async()=>{const body=Object.fromEntries(new FormData(e.target));const p=await api('/projects',{method:'POST',body:JSON.stringify(body)});e.target.reset();e.target.hidden=true;await openProject(p.id);});};
$('back').onclick=()=>act(home);
$('files').onchange=()=>act(async()=>{busy=true;const id=current.id;$('files').disabled=true;try{for(const file of $('files').files){let u=current.uploads.find(u=>u.name===file.name&&u.size===file.size&&u.status==='uploading');if(!u){const kind=/\.(mp4|mov)$/i.test(file.name)||file.type.startsWith('video/')?'video':'photo';u=await api(`/projects/${id}/uploads`,{method:'POST',body:JSON.stringify({name:file.name,size:file.size,kind})});}await TripUpload.transfer(file,u,id,api,value=>{$('upload-progress').textContent=value;});await api(`/projects/${id}/uploads/${u.id}/complete`,{method:'POST'});await refresh(id);}$('upload-progress').textContent='Your media is uploaded and ready.';}finally{busy=false;$('files').disabled=false;$('files').value='';await refresh(id);}});
$('analysis-form').onsubmit=e=>{e.preventDefault();act(async()=>{await api(`/projects/${current.id}/analyze`,{method:'POST',body:JSON.stringify({request:$('request').value,context:$('context').value})});shownJob=null;await refresh(current.id);$('job-panel').scrollIntoView({behavior:'smooth'});});};
$('cancel').onclick=()=>act(async()=>{await api(`/projects/${current.id}/cancel`,{method:'POST'});$('job-detail').textContent='Stopping the current analysis…';await refresh(current.id);});
$('approval-form').onsubmit=e=>{e.preventDefault();act(async()=>{const moment_ids=[...document.querySelectorAll('input[name=moment]:checked')].map(e=>e.value);if(!moment_ids.length)throw new Error('Select at least one moment.');await api(`/projects/${current.id}/approve`,{method:'POST',body:JSON.stringify({job_id:current.current_job,revision:current.revision,proposal_sha256:proposal.sha256,moment_ids,style:$('style').value,lighting:$('lighting').value,notes:$('notes').value})});await refresh(current.id);$('generation-panel').scrollIntoView({behavior:'smooth',block:'start'});});};
$('delete').onclick=()=>act(async()=>{if(confirm('Delete this project, its media, and its analysis?')){await api(`/projects/${current.id}`,{method:'DELETE'});await home();}});
(async()=>{const id=location.hash.slice(1);try{await session();if(/^[a-f0-9]{32}$/.test(id))await openProject(id);}catch(e){if(!e.message.includes('invitation code'))notice(e.message);}})();
